name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-65ee4677d286b70001d485e8-c6459f1c8a539e5ae50ffcd40b7403a570
      - name: Run API tests
        run: |
          postman collection run 12828671-95f532a8-0a98-480a-8cdf-dbfb44aaa51aPMAK-65ee4677d286b70001d485e8-c6459f1c8a539e5ae50ffcd40b7403a570
