name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key 33434157-55024922-7bfd-44d4-857b-5532eba3df1c
      - name: Run API tests
        run: |
          postman collection run 33434157-55024922-7bfd-44d4-857b-5532eba3df1c -i 33434157-3187189a-1fa9-4c15-9021-8e6871e9588b
