name: Newman Test Run
on:
  push:
    branches:
    - main    
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:      
      - run: npm install -g newman
      - run: newman run '/home/runner/work/HEXA_API_Team_24/Postman Collections/demo.json'
#    - run: newman run "https://api.getpostman.com/collections/${{collectionID}}?apikey=${{ secrets.POSTMANAPIKEY }}" --environment "https://api.getpostman.com/environments/${{ environmentID }}?apikey=${{ secrets.POSTMANAPIKEY }}"

