name: Newman Test Run
on:
  push:
    branches:
    - main    
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:      
      - run: npm install -g newman
      - run: newman run "Postman Collections/demo.json"
