name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main      

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install Node on serve
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    # Install newman and html reporter
    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Make Directory for result
      run: mkdir -p testResults

      
    - name: Run Postman collections
      run: |
        newman run ./Testing/demo.json -g ./env/QA.json -d ./data/data.csv -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme > testResults/runreport1.html
        
    - name: Output the run details
      uses: actions/upload-artifact@v2
      with: 
        name: RunReports
        path: testResults

